sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t kirillprotein/docker-react -f Dockerfile.dev

script:
  - docker run -e CI=true kirillprotein/docker-react npm run test
